$env:SUPABASE_URL="https://test.supabase.co"
$env:SUPABASE_SERVICE_ROLE_KEY="test_key_12345"
$env:JWT_SECRET="test_jwt_secret_that_is_long_enough"
$env:VD_DISTRIBUTOR_ID="VDIDSabbPe"
$env:VD_API_USERNAME="test_user"
$env:VD_API_PASSWORD="test_pass"
$env:VD_SECRET_KEY="0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
$env:VD_SECRET_IV="0123456789abcdef0123456789abcdef"
$env:VD_API_BASE_URL="https://cards.vdwebapi.com"
$env:SABBPE_API_KEY="test_key"
$env:SABBPE_API_SECRET="test_secret"
$env:SABBPE_API_BASE_URL="https://api.sabbpe.com"
$env:SABBPE_WEBHOOK_SECRET="test_webhook_secret"
$env:SABBPE_MERCHANT_ID="VDIDSabbPe"
npm start
